apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort  # 外部公開
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # EC2のパブリックIP:30080でアクセス可能