name: Build and Push to ECR

# トリガー：mainブランチにpushされたとき
on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # GitHubのホストランナーを使用

    steps:
    # ① コードをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v3

    # ② AWS認証を設定（Secretsから取得）
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1  # 東京リージョン

    # ③ ECRにログイン
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # ④ DockerイメージをビルドしてECRにpush
    - name: Build, tag, and push image to ECR
      run: |
        IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/my-nginx-app:latest
        echo "Building Docker image: $IMAGE_URI"
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI