name: CI/CD to ECR and Kubernetes

on:
  push:
    branches: [ main ]  # mainブランチにpushされたら実行

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHubホストランナーを使用

    steps:
    # ① コードをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v3

    # ② AWS認証を設定（Secretsから取得）
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1  # 東京リージョン

    # ③ ECRにログイン
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # ④ DockerイメージをビルドしてECRにpush
    - name: Build and Push Docker Image
      run: |
        IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/my-nginx-app:latest
        echo "Building Docker image: $IMAGE_URI"
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI
    # ⑤ kubectlをセットアップ
    - name: Setup kubectl
      run: |
        echo "${{ secrets.KUBECONFIG_DATA }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    # ⑥ Kubernetesマニフェストを適用
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml